language: swift
osx_image: xcode14.0

before_install:
  - pod repo update
  - pod install

script:
  - xcodebuild clean build -workspace CICD.xcworkspace -scheme CICD -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace CICD.xcworkspace -scheme CICD -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro' CODE_SIGNING_REQUIRED=NO
  - xcodebuild archive -workspace CICD.xcworkspace -scheme CICD -destination 'generic/platform=iOS' -archivePath build/CICD.xcarchive
   - xcodebuild -exportArchive -archivePath build/YourProject.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

before_deploy:
  - mv "build/CICD.ipa" "build/CICD-$TRAVIS_TAG.ipa"

deploy:
  provider: releases
  api_key: $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
  file: "build/CICD-$TRAVIS_TAG.ipa"
  skip_cleanup: true
  on:
    tags: true